language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t gmateosaws/docker-react . 

script:
  - docker run -e CI=true gmateosaws/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  edge: true
  region: "eu-west-3"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket-name: "elasticbeanstalk-eu-west-3-478344394470"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY